### ISSUE TITLE
release/2.0 branch gives OSError: libnvToolsExt: ELF load command address/offset not properly aligned

### ISSUE THREAD

**Issue by ajindal1** [pytorch/builder#1359]
Current issue summary:
1. release/2.0 branch of builder repo with Pytorch release/2.0 branch gives the below error
2. main branch of builder repo with Pytorch release/2.0 branch is working fine

OS and other details:
Ubuntu 20.04
Pytorch 2.0
CUDA 11.7
CUDNN 8.5.0

While using the latest release/2.0 branch from builder and Pytorch, I am unable to build the Torch 2.0 image. The error first shows up while building Torch 2.0 from source with MPI but did not break the pipeline. However, after installing Pytorch and running "import torch" gives the error again. The error details are as follows.
Steps followed:
1. Using Builder release/2.0 branch, Pytorch release/2.0 branch
2. Build base docker image from builder repo using this command:
`GPU_ARCH_TYPE=cuda GPU_ARCH_VERSION=${DESIRED_CUDA:0:2}.${DESIRED_CUDA:2:1} manywheel/build_docker.sh`
3. Build Pytorch from source with MPI on the above base image, gives the below error at this step. The error comes silently and doesn't break the pipeline. There are 11 errors on "error while loading shared libraries" for libnvToolsExt-847d78f2.so.1, libgomp-a34b3233.so.1, libnvrtc-d833c4f3.so.11.2, libcudart-e409450e.so.11.0. Logs:
Successfully installed torch-2.0.0
++ for installed_lib in '"${installed_libraries[@]}"'
++ ldd /opt/python/cp38-cp38/lib/python3.8/site-packages/torch/_C_flatbuffer.cpython-38-x86_64-linux-gnu.so
/opt/python/cp38-cp38/lib/python3.8/site-packages/torch/_C_flatbuffer.cpython-38-x86_64-linux-gnu.so: error while loading shared libraries: libnvToolsExt-847d78f2.so.1: ELF load command address/offset not properly aligned
/opt/python/cp38-cp38/lib/python3.8/site-packages/torch/_C.cpython-38-x86_64-linux-gnu.so: error while loading shared libraries: libnvToolsExt-847d78f2.so.1: ELF load command address/offset not properly aligned
4. Install Pytorch which was build in the previous step.
5. Run `import torch` and it throws the below error.
++ python -c 'import torch;print(torch.__version__)'
Traceback (most recent call last):
File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/__init__.py", line 168, in _load_global_deps
ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
File "/opt/conda/envs/ptca/lib/python3.8/ctypes/__init__.py", line 373, in _init
self._handle = _dlopen(self._name, mode)
OSError: libnvToolsExt-847d78f2.so.1: ELF load command address/offset not properly aligned
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/__init__.py", line 228, in <module>
_load_global_deps()
File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/__init__.py", line 189, in _load_global_deps
_preload_cuda_deps(lib_folder, lib_name)
File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/__init__.py", line 154, in _preload_cuda_deps
raise ValueError(f"{lib_name} not found in the system path {sys.path}")
ValueError: libcublas.so.*[0-9] not found in the system path ['', '/opt/conda/envs/ptca/lib/python38.zip', '/opt/conda/envs/ptca/lib/python3.8', '/opt/conda/envs/ptca/lib/python3.8/lib-dynload', '/opt/conda/envs/ptca/lib/python3.8/site-packages']

**Comment by ajindal1** [comment]
Is it okay for us to use the main branch of builder repo with triton version set to 2.0 for building Pytorch 2.0?

**Comment by malfet** [comment]
@ajindal1 can you please share the exact command that is failing for you? But yes, at the moment there are no difference between manywheel docker images build on trunk vs release/2.0 branch

**Comment by ajindal1** [comment]
There is no failure while running `import torch` but it gives the above error and continues. Our code fails because it wants to find out torch version and unable to get it. The return value of the below code is nothing, which is unexpected and causes error in our pipeline because PYTORCH_VERSION is not set.
`export PYTORCH_VERSION=$(python -c "import torch;print(torch.__version__)")`

**Comment by ajindal1** [comment]
Reproduction steps (not including every line of code but just adding comments to reduce the size). Please let me know if you need more information anywhere.
```
# Clone builder and pytorch repo and check out to release/2.0 branch
git clone https://github.com/pytorch/pytorch.git
git clone https://github.com/pytorch/builder.git
# Run git submodule and update for pytorch
# Building base image using builder repo
cd builder
GPU_ARCH_TYPE=cuda GPU_ARCH_VERSION=11.7 manywheel/build_docker.sh
# Clone Msccl repo (it is an extension of NCCL, but otherwise no changes): https://github.com/microsoft/msccl
# Using MSCCL instead of NCCL:
cd pytorch
perl -p -i -e  's/url = https:\/\/github\.com\/NVIDIA\/nccl/url = https:\/\/github\.com\/microsoft\/msccl/g' .gitmodules
git submodule sync third_party/nccl
git submodule update --init --recursive --remote third_party/nccl
# Apply MSSCL patch for torch: https://github.com/microsoft/msccl/blob/master/patches/torch1.13.nccl.cpp.patch
# Inside docker image build above, run the following steps:
# Remove libnccl and build msccl (this is done because MSCCL has a dependency on NCCL 2.12.12)
yum remove -y libnccl*
cd /msccl/
make -j src.build
# Download and Install HPCX MPI using private URL
wget --no-verbose --retry-connrefused --tries=3 --waitretry=5 -O $TARBALL $HPCX_DOWNLOAD_URL
tar -xf ${TARBALL} && rm -rf ${TARBALL}
# copy over ompi and ucx
HPCX_DIR=/opt/hpcx
HPCX_MPI_DIR=${HPCX_DIR}/ompi
HPCX_UCX_DIR=${HPCX_DIR}/ucx
mkdir -p ${HPCX_DIR}
mv ${HPCX_FOLDER}/ompi ${HPCX_DIR}/ompi 
mv ${HPCX_FOLDER}/ucx ${HPCX_DIR}/ucx 
rm -rf ${HPCX_FOLDER}
# create symbolic links for /usr/local/mpi and /usr/local/
# Enable OpenMPI's mpirun package to run as root
# set library path for openmpi and ucx, and run ldconfig
# using ldconf and .conf files to set paths to mpi correctly (even for non-root users)
echo "${HPCX_MPI_DIR}/lib
${HPCX_UCX_DIR}/lib" >> /etc/ld.so.conf.d/hpcx_ompi_ucx.conf
ldconfig
source /etc/profile.d/hpcx_ompi_ucx.sh
# Install mpi4py (OpenMPI Python package)
python -m pip install mpi4py
# Run build command for Pytorch
source /builder/manywheel/build.sh
```
