### ISSUE TITLE
magma-cuda102 missing from soumith channel

### ISSUE THREAD

**Issue by jayenashar** [pytorch/builder#549]
I'm trying to build a version of pytorch for CUDA 10.2 and I normally use `build_multiple.sh` but it's not working this time.

I see 10.0 and 10.1: https://anaconda.org/search?q=magma-cuda10

Building for https://github.com/pytorch/pytorch/issues/30532#issuecomment-706715333

**Comment by jayenashar** [comment]
workaround:

```
--- a/conda/build_pytorch.sh
+++ b/conda/build_pytorch.sh
@@ -79,7 +79,7 @@ if [ -z "$ANACONDA_TOKEN" ]; then
 fi
 if [[ -z "$ANACONDA_USER" ]]; then
     # This is the channel that finished packages will be uploaded to
-    ANACONDA_USER=soumith
+    ANACONDA_USER=pytorch
 fi
 if [[ -z "$GITHUB_ORG" ]]; then
     GITHUB_ORG='pytorch'
```

**Comment by jayenashar** [comment]
:(  somehow that made things worse:

```
Checking that we are testing the package that is just built
+ python -c 'import torch; exit(0 if torch.__version__ == '\''1.6.0'\'' else 1)'
+ [[ cu102 != \c\p\u ]]
+ echo 'Checking that CUDA archs are setup correctly'
+ timeout 20 python -c 'import torch; torch.randn([3,5]).cuda()'
Checking that CUDA archs are setup correctly
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/env_py3.7_cuda_cudnn_0_20201011/lib/python3.7/site-packages/torch/cuda/__init__.py", line 186, in _lazy_init
    _check_driver()
  File "/opt/conda/envs/env_py3.7_cuda_cudnn_0_20201011/lib/python3.7/site-packages/torch/cuda/__init__.py", line 61, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by UlrichFreitag** [comment]
It seems to be present now: https://anaconda.org/pytorch/magma-cuda102

**Comment by jayenashar** [comment]
that's the pytorch channel.  this repo points to @soumith's channel

**Comment by soumith** [comment]
@jayenashar it used to a long time ago, but the scripts now don't. you should be using the `pytorch` conda channel.

**Comment by jayenashar** [comment]
https://github.com/pytorch/builder/blob/master/conda/build_pytorch.sh#L82 says `soumith` and when i change it to `pytorch` (https://github.com/pytorch/builder/issues/549#issuecomment-706782868 ), it does build, but cuda is still missing (https://github.com/pytorch/builder/issues/549#issuecomment-706805425 )
